import "~/styles/globals.css";
import HeaderNavigation from "~/app/_components/HeaderNavigation";

import { Inter } from "next/font/google";
// import { cookies } from "next/headers";

import { TRPCReactProvider } from "~/trpc/react";

export const revalidate = 30;

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Gazeta Esportiva",
  description: "Generated by Odds",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <HeaderNavigation />
        {/* <TRPCReactProvider cookies={cookies().toString()}> */}
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
